export const APPLICATION_LEADS = 'APPLICATION_LEADS';
export const APPLICATION_COUNT = 'APPLICATION_COUNT';
export const APPLICATION_PROG = 'APPLICATION_PROG';
export const TOTAL_STUDENT_ENROLLED = 'TOTAL_STUDENT_ENROLLED';
export const ELIGIBILITY_ASSESSMENT = 'ELIGIBILITY_ASSESSMENT';
export const INCOMPLETE_REGISTRATIONS = 'INCOMPLETE_REGISTRATIONS';
export const PENDING_VISA = 'PENDING_VISA';
export const PENDING_ACCOMODATION = 'PENDING_ACCOMODATION';
export const PENDING_ENROLLMENT = 'PENDING_ENROLLMENT';
export const APPLICATION_DETAIL = 'APPLICATION_DETAIL';
export const APPLICATION_PROG_DETAIL = 'APPLICATION_PROG_DETAIL';
export const STEPS_LIST_DATA = 'STEPS_LIST_DATA';
export const STEPS_DETAIL_DATA = 'STEPS_DETAIL_DATA';
export const APPLICATIONS_LIST = 'APPLICATIONS_LIST';
export const TOTAL_RECRUITMENT = 'TOTAL_RECRUITMENT';
export const MARKETING_APPLICATION = 'MARKETING_APPLICATION';
export const MARKETING_SEARCH = 'MARKETING_SEARCH';
export const EMPTY_APP = 'EMPTY_APP';
export const EMPTY_APP_LIST = 'EMPTY_APP_LIST';


export const LECTURER_TODAY_SCHEDULE = 'LECTURER_TODAY_SCHEDULE';
export const TEAM_MODULES_LIST = 'TEAM_MODULES_LIST';

export const FACULTY_PROGRESS = 'FACULTY_PROGRESS';
export const FACULTY_CALENDAR = 'FACULTY_CALENDAR';
export const FACULTY_CALENDAR_WEEKLY = 'FACULTY_CALENDAR_WEEKLY';
export const FACULTY_REQUESTS = 'FACULTY_REQUESTS';
export const FACULTY_STUDENT_TO_ASSIST = 'FACULTY_STUDENT_TO_ASSIST';
export const FACULTY_MODULES = 'FACULTY_MODULES';
export const FACULTY_SUBMISSIONS = 'FACULTY_SUBMISSIONS';
export const FACULTY_PENDING_GRADING = 'FACULTY_PENDING_GRADING';
export const DOCUMENT_DOWNLOAD_LIST = 'DOCUMENT_DOWNLOAD_LIST';
export const ELIGIBILITY_ARCHIVE = 'ELIGIBILITY_ARCHIVE';
