export const OTHER_ISSUES = 'OTHER_ISSUES';
export const MODULE_LIST = 'MODULE_LIST';
export const PENDING_LIST = 'PENDING_LIST';
export const STAFF_ISSUES = 'STAFF_ISSUES';
export const GET_FACULTY_TIMETABLE = "GET_FACULTY_TIMETABLE";
export const GET_CLOCKIN_CLOCKOUT = "GET_CLOCKIN_CLOCKOUT";
