//Sholarship section
export const FINANCE_SCHOLARSHIP_CARD = "FINANCE_SCHOLARSHIP_CARD";
export const FINANCE_SCHOLARSHIP_LIST = "FINANCE_SCHOLARSHIP_LIST";
export const FINANCE_SCHOLARSHIP_PENDING_CARD = "FINANCE_SCHOLARSHIP_PENDING_CARD";
export const FINANCE_SCHOLARSHIP_PENDING_LIST = "FINANCE_SCHOLARSHIP_PENDING_LIST";


//Applicant section
export const FINANCE_APPLICANT_CARD = "FINANCE_APPLICANT_CARD";
export const FINANCE_APPLICANT_LIST = "FINANCE_APPLICANT_LIST";

//Students section
export const FINANCE_STUDENT_CARD = "FINANCE_STUDENT_CARD";
export const FINANCE_STUDENT_LIST = "FINANCE_STUDENT_LIST";
export const FINANCE_STUDENT_REQUESTS = "FINANCE_STUDENT_REQUESTS";

//Grants section
export const FINANCE_GRANTS_CARD = "FINANCE_GRANTS_CARD";
export const FINANCE_GRANTS_LIST = "FINANCE_GRANTS_LIST";
export const FINANCE_GRANT_PAYMENT_DETAIL = 'FINANCE_GRANT_PAYMENT_DETAIL';

//Transaction section
export const FINANCE_TRANSACTION_LIST = "FINANCE_TRANSACTION_LIST";
export const DROPDOWN_STUDENT_NAME = 'DROPDOWN_STUDENT_NAME';
export const DROPDOWN_STUDENT_ID = 'DROPDOWN_STUDENT_ID';
export const FINANCE_TRANSACTION_CASH_LIST = 'FINANCE_TRANSACTION_CASH_LIST';
export const FINANCE_TRANSACTION_DETAIL = 'FINANCE_TRANSACTION_DETAIL';


export const FINANCE_GRANT_REQUEST = 'FINANCE_GRANT_REQUEST';
export const FINANCE_SCHOLARSHIP_REQUEST = 'FINANCE_SCHOLARSHIP_REQUEST';
export const REGISTRATION_FEE = 'REGISTRATION_FEE';
export const EMPTY_OTHER_REQ = 'EMPTY_OTHER_REQ';
export const COUNTRY_BYFEE = "COUNTRY_BYFEE";
export const SORTING_LIST = "SORTING_LIST";

export const EMPTY_TRANS = "EMPTY_TRANS";


