const docmentType = [
  { label: "Student Profile", value: "Student Profile"},
  { label: "Application Form", value: "Application Form"},
  { label: "Offer Letter", value: "Offer Letter"},
  { label: "Acceptance of Offer Letter", value: "Acceptance of Offer Letter"},
  { label: "Scholarship Letter from Sponsor", value: "Scholarship Letter from Sponsor"},
  { label: "Tuition Fee Receipt", value: "Tuition Fee Receipt"},
  { label: "Programme Approval Letter (KPT & MQA)", value: "Programme Approval Letter (KPT & MQA)"},
  { label: "Financial Statement (Bank Statement)", value: "Financial Statement (Bank Statement)"},
  { label: "Passport Pages with certified true copy", value: "Passport Pages with certified true copy"},
  { label: "IM14 Form", value: "IM14 Form"},
  { label: "Visa Approval Letter (VAL)", value: "Visa Approval Letter (VAL)"},
  { label: "Personal Bond", value: "Personal Bond"},
  { label: "IM55 Form", value: "IM55 Form"},
  { label: "Visa Sticker Endorsement Receipt", value: "Visa Sticker Endorsement Receipt"},
  { label: "Visa Sticker", value: "Visa Sticker"},
  { label: "Email Reminder", value: "Email Reminder"},
  { label: "Visa Clearance Documents", value: "Visa Clearance Documents"},
  { label: "Cancellation Documents", value: "Cancellation Documents"},
  { label: "Police Report", value: "Police Report"},
  { label: "JIM Cancellation", value: "JIM Cancellation"},
  { label: "JIM Tracking", value: "JIM Tracking"},
  { label: "Embassy Email", value: "Embassy Email"},
  { label: "Communication Reach", value: "Communication Reach"},
  { label: "Attendance Report", value: "Attendance Report"},
  { label: "Class Time Table", value: "Class Time Table"},
  { label: "Academic Transcript", value: "Academic Transcript"},

  { label: "Course Advising Form", value: "Course Advising Form"},
  { label: "Academic Qualification", value: "Academic Qualification"},
  { label: "Completion Letter", value: "Completion Letter"},
  { label: "Official Academic Transcript", value: "Official Academic Transcript"},
  { label: "Certificate", value: "Certificate"},
  { label: "Academic Appeal", value: "Academic Appeal"},
  { label: "Deferment Form", value: "Deferment Form"},

  { label: "Termination Letter", value: "Termination Letter"},
  { label: "Copy of Insurance Policy", value: "Copy of Insurance Policy"},
  { label: "Pre Medical Report", value: "Pre Medical Report"},
  { label: "Release Letter", value: "Release Letter"},
  { label: "Orientation Program", value: "Orientation Program"},
  { label: "Personal Data Protection Acts (PDPA) - Acceptance", value: "Personal Data Protection Acts (PDPA) - Acceptance"},
  { label: "Student Manual Book & Refund Policy", value: "Student Manual Book & Refund Policy"},
  { label: "Warning Letter", value: "Warning Letter"},
  { label: "Barred Letter", value: "Barred Letter"},
  { label: "Leave Application (Medical certificate/ Emergency and etc)", value: "Leave Application (Medical certificate/ Emergency and etc)"},

  { label: "Student Counselling Report", value: "Student Counselling Report"},


  { label: "Resume/CV", value: "CV"},
  { label: "IC/Passport (Scanned)", value: "IC/Passport (Scanned)"},
  { label: "Passport Photo with White Background", value: "Passport Photo with White Background"},
  { label: "Student Consent for Progression", value: "Student Consent for Progression"},
  { label: "Exit stamp", value: "Exit stamp"},
  { label: "Medical Check-up", value: "Medical Check-up"},
  { label: "Sponsorship Recommendation Letter", value: "Sponsorship Recommendation Letter"},
  { label: "Undertaking Letter", value: "Undertaking Letter"},
  { label: "Affidavit Letter", value: "Affidavit Letter"},
  { label: "Certified true copy of Higher Education result & certificate (original & translated)", value: "Certified true copy of Higher Education result & certificate (original & translated)"},
  { label: "Portfolio", value: "Portfolio"},
  { label: "6 Passport Size photograph with blue background (3.5cmx5cm)", value: "6 Passport Size photograph with blue background (3.5cmx5cm)"},
  { label: "2 Passport Copies including all blank pages", value: "2 Passport Copies including all blank pages"},
  { label: "Proof of English Language Proficiency (IELTS/TOEFL)", value: "Proof of English Language Proficiency (IELTS/TOEFL)"},
  { label: "Certified copies of High School result (original & translated)", value: "Certified copies of High School result (original & translated)"}
]

export { docmentType };
 