export const INTAKES_LIST = "INTAKES_LIST";
export const INCENTIVE_LIST = "INCENTIVE_LIST";
export const INCENTIVE_DATA = "INCENTIVE_DATA";
export const INCENTIVE_STUDENT_LIST = "INCENTIVE_STUDENT_LIST";