export const SCHEDULE = 'SCHEDULE';
export const REPLACEMENT_CLASS = 'REPLACEMENT_CLASS';
export const MODULE_FACTS = 'MODULE_FACTS';
export const UNGRADEDSTUDENT_MODULE_LISTS = 'UNGRADEDSTUDENT_MODULE_LISTS';
export const MODULE_ATTENDANCE = 'MODULE_ATTENDANCE';
export const MODULE_TIMETABLE = 'MODULE_TIMETABLE';
export const MODULE_MATERIAL = 'MODULE_MATERIAL';
export const MODULE_ASSESSMENT = 'MODULE_ASSESSMENT';
export const MODULE_ASSESSMENT_DETAILS = 'MODULE_ASSESSMENT_DETAILS';

export const LECTURER_ATTENDANCE = 'LECTURER_ATTENDANCE';
export const STUDENT_ATTENDANCE = 'STUDENT_ATTENDANCE';

export const MODULE_ASSESSMENT_PHD = 'MODULE_ASSESSMENT_PHD';
export const MODULE_ASSESSMENT_DETAILS_PHD = 'MODULE_ASSESSMENT_DETAILS_PHD';
