export const OVERALL_GRANTS_LIST = "OVERALL_GRANTS_LIST";
export const GRANT_SINGLE = "GRANT_SINGLE";
export const GRANTS_LIST_BY_STATUS = "GRANTS_LIST_BY_STATUS";
export const GRANTS_OVERALL_GRAPH = "GRANTS_OVERALL_GRAPH";
export const GRANTS_MY_GRAPH = "GRANTS_MY_GRAPH";