export const STUDENT_PENDING_ISSUES = "STUDENT_PENDING_ISSUES";
export const STUDENT_COMPLAINTS_LIST = "STUDENT_COMPLAINTS_LIST";
export const STUDENT_COMPLAINTS_CARD = "STUDENT_COMPLAINTS_CARD";
export const STUDENT_ISSUES_CARD = "STUDENT_ISSUES_CARD";
export const STUDENT_ISSUES_LIST = "STUDENT_ISSUES_LIST";