export const FACULTY_LIST = "FACULTY_LIST";
export const FACULTY_LIST2 = "FACULTY_LIST2";
export const INTITUTION_LIST = "INTITUTION_LIST";
export const SINGLE_FACULTY = "SINGLE_FACULTY";
export const PROGRAM_LIST = "PROGRAM_LIST";