export const FACULTY_MODULES = 'FACULTY_MODULES';
export const MODULE_SUMMARY = 'MODULE_SUMMARY';
export const MODULE_LECTURER = 'MODULE_LECTURER';
export const MODULE_STUDENTS = 'MODULE_STUDENTS';
export const MODULE_MATERIALS = 'MODULE_MATERIALS';
export const MODULE_TIMETABLE = 'MODULE_TIMETABLE';
export const MODULE_GRAPH = 'MODULE_GRAPH';