export const TIMETABLE_LIST = "TIMETABLE_LIST";
export const TIMETABLE_DETAILS = "TIMETABLE_DETAILS";
export const UNASSIGN_MODULES = "UNASSIGN_MODULES";
export const CLASSROOM_TYPE = "CLASSROOM_TYPE";
export const CLASSROOMS = "CLASSROOMS";
export const UNASSIGNED_STUDENTS = "UNASSIGNED_STUDENTS";
export const TIMETABLE_LECTURERS = "TIMETABLE_LECTURERS";

export const RESET_TIMETABLE = "RESET_TIMETABLE";