export const OVERALL_PUBLICATIONS_LIST = "OVERALL_PUBLICATIONS_LIST";
export const PUBLICATION_SINGLE = "PUBLICATION_SINGLE";
export const PUBLICATIONS_LIST_BY_STATUS = "PUBLICATIONS_LIST_BY_STATUS";
export const PUBLICATIONS_OVERALL_GRAPH = "PUBLICATIONS_OVERALL_GRAPH";
export const PUBLICATIONS_MY_GRAPH = "PUBLICATIONS_MY_GRAPH";
export const PROGRAM_LIST = "PROGRAM_LIST";
