export const AUDIT_LIST = 'AUDIT_LIST';
export const AUDITED_LIST = 'AUDITED_LIST';
export const MISSING_DOCS_COUNT = 'MISSING_DOCS_COUNT';
export const RESET_AUDIT_LIST = 'RESET_AUDIT_LIST';
export const DOCUMENT_LIST = 'DOCUMENT_LIST';
export const STUDENTBY_STATUS = 'STUDENTBY_STATUS';