export default {
    MARKETING: {
        APPLICATION: 'cms_marketing_applications',
        INCENTIVE: 'cms_marketing_incentive',
        STUDENTS: 'cms_marketing_students',
        SETUP: 'cms_marketing_customize',
        MANAGER: 'cms_marketing_manager',
    },
    FINANCE: {
        TRANSACTION: 'finance_transaction',
        APPLICANTS: 'finance_applicants',
        STUDENTS: 'finance_students',
        SCHOLARSHIP: 'finance_scholarships',
        GRANTS: 'finance_grants',
        SETUP: 'finance_setup',
        MANAGER: 'finance_manager',
    },
    ELIGIBILITY: {
        APPLICATION: 'eligibility_applications',
        MANAGER: 'eligibility_manager',
    },
    REGISTRY: {
        STUDENTS: 'registry_students',
        REQUESTS: 'registry_requests',
        SCHOLARSHIP: 'registry_scholarship',
        SETUP: 'registry_setup',
        MANAGER: 'registry_manager',
    },
    AQA: {
        FACULTY: 'aqa_faculty',
        PROGRAMMES: 'aqa_programmes',
        MODULES: 'aqa_modules',
        REQUESTS: 'aqa_requests',
        FORMS: 'aqa_forms',
        CALENDAR: 'aqa_calendar',
        INCENTIVE: 'aqa_incentives',
        SETUP: 'aqa_setup',
        MANAGER: 'aqa_manager',
    },
    FACULTY: {
        LECTURER: 'faculty_lecturers',
        PROGRAMMES: 'faculty_programmes',
        MODULES: 'faculty_modules',
        STUDENTS: 'faculty_students',
        TIMETABLE: 'faculty_timetable',
        EXAMS: 'faculty_exams',
        CLASSROOM: 'faculty_classroom',
        VIRTUALCLASS: 'faculty_virtualclass',
        MATERIALS: 'faculty_materials',
        GRANTS: 'faculty_grants',
        PUBLICATIONS: 'faculty_publications',
        REQUESTS: 'faculty_requests',
        SETUP: 'faculty_setup',
        MANAGER: 'faculty_manager',
        DEAN: 'faculty_dean',
    },
    STUDENT: {
        INTERNAL: 'internal_office',
        AUDIT: 'audit'
    }
}