import AllRoles from './AllRoles';

const titles = {
  Eligibility: 'Eligibility',
};

export const Eligibility = [
    {
        component: 'Overview',
        path: '/eligibility/overview',
        title: titles.Eligibility,
        permission: [AllRoles.ELIGIBILITY.APPLICATION],
        key: 'eligibility',
        menu: 'Eligibility Assesment',
        submenu: 'Applications',
        icon: 'OverviewIcon',
        parent: true,
      },
      {
        component: 'EditApplication',
        path: '/eligibility/applications/eligibility-assessments/:id',
        title: titles.Eligibility,
        permission: [AllRoles.ELIGIBILITY.APPLICATION],
        key: 'eligibility',
        menu: 'Eligibility Assesment',
        submenu: 'Application',
        parent: false,
      },
      // {
      //   component: 'ApplicationsList',
      //   path: '/marketing/applications',
      //   title: titles.MARKETING,
      //   permission: marketing,
      //   key: 'marketing',
      //   menu: 'Marketing',
      //   submenu: 'Application',
      //   icon: 'ApplicationsIcon',
      //   parent: true,
      // },
      // {
      //   component: 'IncompleteApplications',
      //   path: '/marketing/applications/incomplete-applications',
      //   title: titles.MARKETING,
      //   permission: marketing,
      //   key: 'marketing',
      //   menu: 'Marketing',
      //   submenu: 'Application',
      //   parent: false,
      // },
      // {
      //   component: 'AddApplication',
      //   path: '/marketing/applications/addnew',
      //   title: titles.MARKETING,
      //   menu: 'Marketing',
      //   key: 'marketing',
      //   submenu: 'Application',
      //   permission: marketing,
      //   parent: false,
      // },
      // // {
      // //   component: 'EditApplication',
      // //   path: '/marketing/applications/:id',
      // //   title: titles.MARKETING,
      // //   permission: marketing,
      // //   key: 'marketing',
      // //   menu: 'Marketing',
      // //   submenu: 'Application',
      // //   parent: false,
      // // },
      // {
      //   component: 'IncompleteDocuments',
      //   path: '/marketing/applications/incomplete-documents',
      //   title: titles.MARKETING,
      //   permission: marketing,
      //   menu: 'Marketing',
      //   key: 'marketing',
      //   submenu: 'Application',
      //   parent: false,
      // },
      // {
      //   component: 'EditApplication',
      //   path: '/marketing/applications/incomplete-documents/:id',
      //   title: titles.MARKETING,
      //   permission: marketing,
      //   key: 'marketing',
      //   menu: 'Marketing',
      //   submenu: 'Application',
      //   parent: false,
      // },
      // {
      //   component: 'EligibilityAssessments',
      //   path: '/marketing/applications/eligibility-assessments',
      //   title: titles.MARKETING,
      //   permission: marketing,
      //   menu: 'Marketing',
      //   key: 'marketing',
      //   submenu: 'Application',
      //   parent: false,
      // },
      
      // {
      //   component: 'PendingRegistrationsVisa',
      //   path: '/marketing/applications/pending-registration-visa',
      //   title: titles.MARKETING,
      //   permission: marketing,
      //   menu: 'Marketing',
      //   key: 'marketing',
      //   submenu: 'Application',
      //   parent: false,
      // },
      // {
      //   component: 'EditApplication',
      //   path: '/marketing/applications/pending-registration-visa/:id',
      //   title: titles.MARKETING,
      //   permission: marketing,
      //   menu: 'Marketing',
      //   key: 'marketing',
      //   submenu: 'Application',
      //   parent: false,
      // },
      // {
      //   component: 'PendingAccommodations',
      //   path: '/marketing/applications/pending-accommodations',
      //   title: titles.MARKETING,
      //   permission: marketing,
      //   menu: 'Marketing',
      //   key: 'marketing',
      //   submenu: 'Application',
      //   parent: false,
      // },
      // {
      //   component: 'EditApplication',
      //   path: '/marketing/applications/pending-accommodations/:id',
      //   title: titles.MARKETING,
      //   permission: marketing,
      //   menu: 'Marketing',
      //   key: 'marketing',
      //   submenu: 'Application',
      //   parent: false,
      // },
      // {
      //   component: 'PendingEnrolment',
      //   path: '/marketing/applications/pending-enrolment',
      //   title: titles.MARKETING,
      //   permission: marketing,
      //   menu: 'Marketing',
      //   key: 'marketing',
      //   submenu: 'Application',
      //   parent: false,
      // },
      // {
      //   component: 'EditApplication',
      //   path: '/marketing/applications/pending-enrolment/:id',
      //   title: titles.MARKETING,
      //   permission: marketing,
      //   menu: 'Marketing',
      //   key: 'marketing',
      //   submenu: 'Application',
      //   parent: false,
      // },
]