import AllRoles from './AllRoles';

const titles = {
  FACULTY: 'Faculty',
};

const roles = {
  programmes: [AllRoles.FACULTY.PROGRAMMES],
  lecturer: [AllRoles.FACULTY.LECTURER],
  modules: [AllRoles.FACULTY.MODULES],
  students: [AllRoles.FACULTY.STUDENTS],
  setup: [AllRoles.FACULTY.SETUP],
  materials: [AllRoles.FACULTY.MATERIALS],
  grants: [AllRoles.FACULTY.GRANTS],
  publications: [AllRoles.FACULTY.PUBLICATIONS],
  requests: [AllRoles.FACULTY.REQUESTS],
  exams: [AllRoles.FACULTY.EXAMS],
  timetable: [AllRoles.FACULTY.TIMETABLE],
  classroom: [AllRoles.FACULTY.CLASSROOM],
  virtualclass: [AllRoles.FACULTY.VIRTUALCLASS],
}

export const Faculty = [
  {
    component: 'Overview',
    path: '/faculty/overview',
    title: titles.FACULTY,
    permission: roles.programmes,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Overview',
    icon: 'OverviewIcon',
    parent: true,
  },
  {
    component: 'Lecturers',
    path: '/faculty/lecturers',
    title: titles.FACULTY,
    permission: roles.lecturer,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Lecturers',
    icon: 'UserIcon',
    parent: true,
  },
  {
    component: 'StaffIssues',
    path: '/faculty/lecturers/issues',
    title: titles.FACULTY,
    permission: roles.lecturer,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Lecturers',
    parent: false,
  },
  {
    component: 'UnassignedStaff',
    path: '/faculty/lecturers/unassigned',
    title: titles.FACULTY,
    permission: roles.lecturer,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Lecturers',
    parent: false,
  },
  {
    component: 'StaffRequests',
    path: '/faculty/lecturers/requests',
    title: titles.FACULTY,
    permission: roles.lecturer,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Lecturers',
    parent: false,
  },
  {
    component: 'StaffDetails',
    path: '/faculty/lecturers/tasks/:id',
    title: titles.FACULTY,
    permission: roles.lecturer,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Lecturers',
    parent: false,
  },
  {
    component: 'StaffMain',
    path: '/faculty/staff/:id',
    title: titles.FACULTY,
    permission: roles.lecturer,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Lecturers',
    parent: false,
  },
  {
    component: 'StudentSection',
    path: '/faculty/lecturers/students/:id',
    title: titles.FACULTY,
    permission: roles.students,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Lecturers',
    parent: false,
  },
  {
    component: 'Programmes',
    path: '/faculty/programmes',
    title: titles.FACULTY,
    permission: roles.programmes,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Programmes',
    icon: 'ProgrammeIcon',
    parent: true,
  },
  {
    component: 'Modules',
    path: '/faculty/modules',
    title: titles.FACULTY,
    permission: roles.modules,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Modules',
    icon: 'ModuleIcon',
    parent: true,
  },
  {
    component: 'ModuleDetails',
    path: '/faculty/modules/:id',
    title: titles.FACULTY,
    permission: roles.modules,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Modules',
    parent: false,
  },
  {
    component: 'Students',
    path: '/faculty/students',
    title: titles.FACULTY,
    permission: roles.students,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Students',
    icon: 'StudentsIcon',
    parent: true,
  },
  {
    component: 'StudentDetails',
    path: '/faculty/students/details/:id',
    title: titles.FACULTY,
    permission: roles.students,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Students',
    parent: false,
  },
  {
    component: 'StudentIssues',
    path: '/faculty/students/issues',
    title: titles.FACULTY,
    permission: roles.students,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Students',
    parent: false,
  },
  {
    component: 'StudentRequests',
    path: '/faculty/students/requests',
    title: titles.FACULTY,
    permission: roles.students,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Students',
    parent: false,
  },
  {
    component: 'StudentComplaints',
    path: '/faculty/students/complaints',
    title: titles.FACULTY,
    permission: roles.students,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Timetable',
    parent: false,
  },
  
  {
        component: 'Timetable',
        path: '/faculty/timetable',
        title: titles.FACULTY,
        permission: roles.timetable,
        key: 'faculty',
        menu: 'Faculty',
        submenu: 'Timetable',
        icon: 'ClockIcon',
        parent: true,
    },
	{
    component: 'EditTable',
    path: '/faculty/timetable/editTimetable/:id',
    title: titles.FACULTY,
    permission: roles.timetable,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Timetable',
    parent: false,
   }, 
  
   {
    component: 'TimetableCards',
    path: '/faculty/timetable/unassignModules',
    title: titles.FACULTY,
    permission: roles.timetable,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Timetable',
    parent: false,
    },
  
  {
    component: 'ProgrammeDetail',
    path: '/faculty/programmes/:id',
    title: titles.FACULTY,
    permission: roles.programmes,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Programmes',
    parent: false,
  },
  {
    component: 'Exams',
    path: '/faculty/exams',
    title: titles.FACULTY,
    permission: roles.exams,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Exams',
    icon: 'ApplicationsIcon',
    parent: true,
  },
  {
    component: 'EditExamTable',
    path: '/faculty/exams/editExam/:id',
    title: titles.FACULTY,
    permission: roles.exams,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Exams',
    parent: false,
  },
  {
    component: 'ExamCards',
    path: '/faculty/exams/unassignModules',
    title: titles.FACULTY,
    permission: roles.exams,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Exams',
    parent: false,
  },
  {
    component: 'Classroom',
    path: '/faculty/classroom',
    title: titles.FACULTY,
    permission: roles.classroom,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Classroom',
    icon: 'ClassroomIcon',
    parent: true,
  },
  {
    component: 'VirtualClass',
    path: '/faculty/virtual-class',
    title: titles.FACULTY,
    permission: roles.virtualclass,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Virtual Class',
    icon: 'ClassroomIcon',
    parent: false,
  },
  {
    component: 'StudentAssessment',
    path: '/faculty/classroom/StudentAssessment/:id',
    title: titles.FACULTY,
    permission: roles.classroom,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Classroom',
    parent: false,
  },
  {
    component: 'UngradedStudents',
    path: '/faculty/classroom/UngradedStudents/:id',
    title: titles.FACULTY,
    permission: roles.classroom,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Classroom',
    parent: false,
  },
  {
    component: 'Materials',
    path: '/faculty/materials',
    title: titles.FACULTY,
    permission: roles.materials,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Materials',
    icon: 'MaterialsIcon',
    parent: true,
  },
  {
    component: 'MaterialDetails',
    path: '/faculty/materials/:id',
    title: titles.FACULTY,
    permission: roles.materials,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Materials',
    parent: false,
  },

  {
    component: 'Grants',
    path: '/faculty/grants',
    title: titles.FACULTY,
    permission: roles.grants,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Grants',
    icon: 'GrantsIcon',
    parent: true,
  },
  {
    component: 'AddGrants',
    path: '/faculty/grants/addgrants',
    title: titles.FACULTY,
    permission: roles.grants,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Grants',
    parent: false,
  },
  
  {
    component: 'EditGrants',
    path: '/faculty/grants/:id',
    title: titles.FACULTY,
    permission: roles.grants,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Grants',
    parent: false,
  },

  {
    component: 'Publications',
    path: '/faculty/publications',
    title: titles.FACULTY,
    permission: roles.publications,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Publications',
    icon: 'PublicationsIcon',
    parent: true,
  },
  {
    component: 'AddPublications',
    path: '/faculty/publications/addpublications',
    title: titles.FACULTY,
    permission: roles.publications,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Publications',
    parent: false,
  },
  {
    component: 'EditPublications',
    path: '/faculty/publications/:id',
    title: titles.FACULTY,
    permission: roles.publications,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Publications',
    parent: false,
  },
  {
    component: 'Requests',
    path: '/faculty/requests',
    title: titles.FACULTY,
    permission: roles.requests,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Requests',
    icon: 'RequestIcon',
    parent: true,
  },
  {
    component: 'AddRequest',
    path: '/faculty/requests/addnew',
    title: titles.FACULTY,
    permission: roles.requests,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Requests',
    parent: false,
  },
  {
    component: 'RequestDetails',
    path: '/faculty/requests/:id',
    title: titles.FACULTY,
    permission: roles.requests,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Requests',
    parent: false,
  },
  // {
  //   component: 'Reports',
  //   path: '/faculty/reports',
  //   title: titles.FACULTY,
  //   permission: faculty,
  //   key: 'faculty',
  //   menu: 'Faculty',
  //   submenu: 'Reports',
  //   icon: 'ReportsIcon',
  //   parent: true,
  // },
  {
    component: 'Setup',
    path: '/faculty/setup',
    title: titles.FACULTY,
    permission: roles.setup,
    key: 'faculty',
    menu: 'Faculty',
    submenu: 'Setup',
    icon: 'SetupIcon',
    parent: true,
  },
];
