import Roles from "./Roles";

const titles = {
  HRMS: 'HRMS',
};

export const HRMS = [
  {
    component: 'Tasks',
    path: '/hrms/tasks',
    title: titles.HRMS,
    permission: [Roles.TASK_INDIVIDUAL],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Tasks',
    icon: 'TaskIcon',
    parent: true,
  },
  {
    component: 'TaskDetail',
    path: '/hrms/tasks/:id',
    title: titles.HRMS,
    permission: [Roles.TASK, Roles.TASK_TEAMS],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Tasks',
    parent: false,
  },
  {
    component: 'Advancement',
    path: '/hrms/advancement',
    title: titles.HRMS,
    permission: [Roles.ADVANCEMENT],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Advancement',
    icon: 'AdvancementIcon',
    parent: true,
  },
  {
    component: 'AdvancementDetails',
    path: '/hrms/advancement/:id',
    title: titles.HRMS,
    permission: [Roles.ADVANCEMENT],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Advancement',
    parent: false,
  },
  {
    component: 'Employment',
    path: '/hrms/employment',
    title: titles.HRMS,
    permission: [Roles.EMPLOYMENT],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Employees',
    icon: 'StaffIcon',
    parent: true,
  },
  {
    component: 'AddEmployment',
    path: '/hrms/employment/add',
    title: titles.HRMS,
    permission: [Roles.EMPLOYMENT],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Employees',
    parent: false,
  },
  {
    component: 'EmploymentDetails',
    path: '/hrms/employment/:id',
    title: titles.HRMS,
    permission: [Roles.EMPLOYMENT],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Employees',
    parent: false,
  },
  {
    component: 'TeamDetails',
    path: '/hrms/employment/team/:id',
    title: titles.HRMS,
    permission: [Roles.EMPLOYMENT],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Employees',
    parent: false,
  },
  {
    component: 'Finance',
    path: '/hrms/finance',
    title: titles.HRMS,
    permission: [Roles.HRMSFINANCE],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Finance',
    icon: 'FacultyIcon',
    parent: true,
  },
  {
    component: 'FinanceDetails',
    path: '/hrms/finance/:id',
    title: titles.HRMS,
    permission: [Roles.HRMSFINANCE],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Finance',
    parent: false,
  },
  {
    component: 'Leaves',
    path: '/hrms/leaves',
    title: titles.HRMS,
    permission: [Roles.LEAVES_INDIVIDUAL],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Leaves',
    icon: 'CalendarIcon',
    parent: true,
  },
  {
    component: 'LeavesDetail',
    path: '/hrms/leaves/:id',
    title: titles.HRMS,
    permission: [Roles.LEAVES, Roles.LEAVES_TEAMS],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Leaves',
    parent: false,
  },
  {
    component: 'Attendance',
    path: '/hrms/attendance',
    title: titles.HRMS,
    permission: [Roles.ATTENDANCE_INDIVIDUAL],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Attendance',
    icon: 'ClockIcon',
    parent: true,
  },
  {
    component: 'EmpAttendanceDetail',
    path: '/hrms/attendance/:id',
    title: titles.HRMS,
    permission: [Roles.ATTENDANCE,Roles.ATTENDANCE_TEAMS],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Attendance',
    parent: false,
  },
  {
    component: 'Policy',
    path: '/hrms/policy',
    title: titles.HRMS,
    permission: [Roles.POLICY],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Policy',
    icon: 'PolicyIcon',
    parent: true,
  },
  {
    component: 'Reports',
    path: '/hrms/reports',
    title: titles.HRMS,
    permission: [Roles.REPORTS],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Reports',
    icon: 'ReportsIcon',
    parent: true,
  },
  {
    component: 'Requests',
    path: '/hrms/requests',
    title: titles.HRMS,
    permission: [Roles.REQUESTS_INDIVIDUAL],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Requests',
    icon: 'RequestIcon',
    parent: true,
  },
  {
    component: 'AddRequest',
    path: '/hrms/requests/addnew',
    title: titles.HRMS,
    permission: [Roles.REQUESTS_INDIVIDUAL],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Requests',
    parent: false,
  },
  {
    component: 'RequestDetails',
    path: '/hrms/requests/:id',
    title: titles.HRMS,
    permission: [Roles.REQUESTS_INDIVIDUAL],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Requests',
    parent: false,
  },
  
  {
    component: 'SetUp',
    path: '/hrms/setup',
    title: titles.HRMS,
    permission: [Roles.SETUP],
    key: 'hrms',
    menu: 'Employment',
    submenu: 'Setup',
    icon: 'SetupIcon',
    parent: true,
  },
  {
    component: 'Profile',
    path: '/myprofile',
    title: titles.HRMS,
    key: 'hrms',
    menu: 'Employment',
    submenu: 'My Profile',
    icon: 'SetupIcon',
    parent: false,
  },
];
