import AllRoles from './AllRoles';

const titles = {
    REGISTRY: 'Registry',
};

export const Registry = [
    {
        component: 'Students',
        path: '/registry/students',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.STUDENTS],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Students',
        icon: 'StudentsIcon',
        parent: true,
        badge: true,
      },
      {
        component: 'Requests',
        path: '/registry/requests',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.REQUESTS],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Requests',
        icon: 'RequestIcon',
        parent: true,
        badge: true,
      },
      {
        component: 'AddRequest',
        path: '/registry/requests/addnew',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.REQUESTS],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Requests',
        parent: false,
      },
      {
        component: 'StudentDetails',
        path: '/registry/requests/:id',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.STUDENTS],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Requests',
        parent: false,
      },
      {
        component: 'ScholarshipList',
        path: '/registry/scholarships',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.SCHOLARSHIP],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Scholarship',
        icon: 'ScholarshipIcon',
        parent: true,
      },
      {
        component: 'AddScholarship',
        path: '/registry/scholarships/addnew',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.SCHOLARSHIP],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Scholarship',
        parent: false,
      },
      {
        component: 'ScholarshipDetail',
        path: '/registry/scholarships/:id',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.SCHOLARSHIP],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Scholarship',
        parent: false,
      },
      {
        component: 'PendingOfferLetter',
        path: '/registry/pending-offerletter',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.STUDENTS],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Students',
        parent: false,
      },
      {
        component: 'PendingRegistration',
        path: '/registry/pending-registration',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.STUDENTS],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Students',
        parent: false,
      },
      {
        component: 'StudentDetails',
        path: '/registry/students/:id',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.STUDENTS],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Students',
        parent: false,
      },
      {
        component: 'EditApplication',
        path: '/registry/applications/pending-registration-visa/:id',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.STUDENTS],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Students',
        parent: false,
      },
      {
        component: 'EditApplication',
        path: '/registry/applications/pending-enrolment/:id',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.STUDENTS],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Students',
        parent: false,
      },

      {
        component: 'Personal',
        path: '/registry/students/personal/:id',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.STUDENTS, AllRoles.MARKETING.STUDENTS, AllRoles.FINANCE.STUDENTS, AllRoles.FACULTY.STUDENTS],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Students',
        parent: false,
      },
      {
        component: 'Academic',
        path: '/registry/students/academic/:id',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.STUDENTS, AllRoles.MARKETING.STUDENTS, AllRoles.FINANCE.STUDENTS, AllRoles.FACULTY.STUDENTS],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Students',
        parent: false,
      },
      {
        component: 'Transcript',
        path: '/registry/students/transcript/:id',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.STUDENTS, AllRoles.MARKETING.STUDENTS, AllRoles.FINANCE.STUDENTS, AllRoles.FACULTY.STUDENTS],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Students',
        parent: false,
      },
      {
        component: 'Finance',
        path: '/registry/students/finance/:id',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.STUDENTS, AllRoles.MARKETING.STUDENTS, AllRoles.FINANCE.STUDENTS],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Students',
        parent: false,
      },
      {
        component: 'Accommodation',
        path: '/registry/students/accommodation/:id',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.STUDENTS, AllRoles.MARKETING.STUDENTS, AllRoles.FINANCE.STUDENTS],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Students',
        parent: false,
      },
      {
        component: 'Customize',
        path: '/registry/customize',
        title: titles.REGISTRY,
        permission: [AllRoles.REGISTRY.SETUP],
        key: 'registry',
        menu: 'Registry',
        submenu: 'Customize',
        icon: 'SetupIcon',
        parent: true,
      },
      
      // {
      //   component: 'ReportsList',
      //   path: '/registry/reports',
      //   title: titles.REGISTRY,
      //   permission: registry,
      //   key: 'registry',
      //   menu: 'Registry',
      //   submenu: 'Reports',
      //   icon: 'ReportsIcon',
      //   parent: true,
      // },
      // {
      //   component: 'AddReports',
      //   path: '/registry/reports/addnew',
      //   title: titles.REGISTRY,
      //   key: 'registry',
      //   menu: 'Registry',
      //   submenu: 'Reports',
      //   permission: registry,
      //   parent: false,
      // },
]