import AllRoles from './AllRoles';

const titles = {
    STUDENTFILE: 'StudentFile',
};

export const StudentFile = [

{
    component: 'Auditor',
    path: '/studentfile/auditor',
    title: titles.STUDENTFILE,
    key: 'studentfile',
    menu: 'Student File',
    submenu: 'Auditor',
    icon: 'PolicyIcon',
    permission: [AllRoles.STUDENT.AUDIT],
    parent: true,
  },
  {
    component: 'InternalOffice',
    path: '/studentfile/internaloffice',
    title: titles.STUDENTFILE,
    key: 'studentfile',
    menu: 'Student File',
    submenu: 'Internal Office',
    icon: 'PolicyIcon',
    permission: [AllRoles.STUDENT.INTERNAL],
    parent: true,
  },
  {
    component: 'StudentDetails',
    path: '/studentfile/internaloffice/students/:id',
    title: titles.STUDENTFILE,
    permission: [AllRoles.STUDENT.INTERNAL],
    key: 'studentfile',
    menu: 'Student File',
    submenu: 'Students',
    parent: false,
  },
  {
    component: 'StudentDetails',
    path: '/studentfile/auditor/students/:id',
    title: titles.STUDENTFILE,
    permission: [AllRoles.STUDENT.AUDIT],
    key: 'studentfile',
    menu: 'Student File',
    submenu: 'Students',
    parent: false,
  },
  {
    component: 'Personal',
    path: '/studentfile/auditor/students/personal/:id',
    title: titles.STUDENTFILE,
    permission: [AllRoles.STUDENT.AUDIT],
    key: 'studentfile',
    menu: 'Student File',
    submenu: 'Students',
    parent: false,
  },
  {
    component: 'Personal',
    path: '/studentfile/students/personal/:id',
    title: titles.STUDENTFILE,
    permission: [AllRoles.STUDENT.INTERNAL],
    key: 'studentfile',
    menu: 'Student File',
    submenu: 'Students',
    parent: false,
  },
  {
    component: 'Academic',
    path: '/studentfile/students/academic/:id',
    title: titles.STUDENTFILE,
    permission: [AllRoles.STUDENT.INTERNAL],
    key: 'studentfile',
    menu: 'Student File',
    submenu: 'Students',
    parent: false,
  },
  {
    component: 'Transcript',
    path: '/studentfile/students/transcript/:id',
    title: titles.STUDENTFILE,
    permission: [AllRoles.STUDENT.INTERNAL],
    key: 'studentfile',
    menu: 'Student File',
    submenu: 'Students',
    parent: false,
  },
  {
    component: 'Finance',
    path: '/studentfile/students/finance/:id',
    title: titles.STUDENTFILE,
    permission: [AllRoles.STUDENT.INTERNAL],
    key: 'studentfile',
    menu: 'Student File',
    submenu: 'Students',
    parent: false,
  },
]